/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6da58e12-c08f-4f87-a954-8ff5f3c38b5c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_riSyXnbVs",
    "aws_user_pools_web_client_id": "f8mmro25pe070cs3chn961if1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://dc5nna2ohbcpffzykqroxf6q5u.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-nlylcqyud5cdxcgjf7tzqd2e4y",
    "aws_user_files_s3_bucket": "productcataloga841deb0dbf546e7baef4c7f9404ebea58056-main",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
